---
title: "R crash course / 02"
author: ""
date: "`r Sys.Date()`"
output:
  ioslides_presentation: default
---

```{r,echo=FALSE}
## Set default options for the knitr RMD processing
knitr::opts_chunk$set(echo=FALSE,warning=FALSE,message=FALSE,fig.width=5,fig.height=5,cache=TRUE,autodep=TRUE, results="hide")
```

## Data matrices

Much like vectors, matrices can only hold one data type (e.g. only numeric
or only character).

```
m <- matrix(1:18, ncol=3, nrow=6)
# compare with
m <- matrix(1:18, ncol=3, nrow=6, byrow=TRUE)
dim(m)
ncol(m)
nrow(m)
```

## Accessing columns, rows and element

`matrix[row, column]`

So, for example:

```
m[1, ] # vector which is the first row
m[, 2] # vector which is the first column
m[3, 1] # first element of the third row
```

## Row and column names

We can name rows and columns of a matrix and use the names to access the
rows and columns:

```
colnames(m) <- letters[1:ncol(m)]
rownames(m) <- LETTERS[1:nrow(m)]

m["A", "b"]
m["B", ] # etc.
```

## Remember

 * If you select a single column or a single row, you will get a vector
 * If you select more than one row or column, you will get a (smaller) matrix
 * If you select more rows or columns than are present, you will get a
   "subscript out of bonds" error

## Matrices and data frames

 Caveats:

  * data frames turn strings to factors, which may have really
    disastrous consequences, use `stringsAsFactors=FALSE`
  * small typos can turn a numeric vector into a string
  * factors are dangerous to work with, use them cautiously

  Gory details: matrices are a basic data type. Data frames are a list.


## Demonstration

## Excercise 2

 * Create a 5x3 matrix with random numbers. Use `matrix` and `rnorm`.
 * Turn the matrix into a data frame. Use `as.data.frame` for that.
 * Add column and row names.
 * Add a column. Each value in the column should be "A" (a string). Use the
   `rep` function for that.
 * Add a column with numbers 1 to 5. Use the `seq` function for that.



